/*
 * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.
 * Licensed under the PolyForm Noncommercial License 1.0.0
 */
#pragma once

/**
 * @file profiling.h
 * @brief Profiling and metrics layer: scan/probe counters and the
 *        cycle-counting instrumentation.
 */

#include "platform/diagnostics.h" // HS_OS_CYCLES, hs::log
#include <cstdint>
#include <cstring>

namespace hs {

/** @brief Scanline profiling counters (platform-agnostic). */
struct ScanMetrics {
  uint32_t pixels_tested = 0; /**< Count of pixels tested. */
  uint32_t pixels_culled = 0; /**< Count of pixels culled before shading. */
  uint32_t exact_hits =
      0; /**< Count of full distance evaluations (umbrella: convex, sector, and exact-walk paths). */
  uint32_t convex_hits =
      0; /**< Count of evaluations on the convex half-plane path. */
  uint32_t sector_hits =
      0; /**< Count of evaluations on the concave sector walk (subset of exact_hits). */
  uint32_t lut_hits = 0; /**< Count of class-LUT bilinear serves. */
  uint32_t plot_backstop_hits =
      0; /**< Count of plot() steps_cache capacity-backstop trips. */
  uint32_t shade_candidates =
      0; /**< Count of pixels passing the scan's d < pixel_width test (shading + alpha-rejected). */
  /** @brief Zeroes every counter. */
  void reset() { *this = {}; }
};
/** @brief Global scanline profiling counters (HS_SCAN_METRICS builds only). */
#ifdef HS_SCAN_METRICS
inline ScanMetrics g_scan_metrics;
#endif

/**
 * @brief Per-probe cycle buckets splitting one Face::distance probe into its
 *        stages, plus the event counts each bucket divides by.
 * @details Raw cycle-counter deltas, one read per stage boundary; `tick` sums
 * a back-to-back read pair per probe to measure the read cost. Report ratios,
 * not absolute times.
 */
struct ProbeBreakdown {
  uint32_t point = 0;       /**< Cycles: probe entry through the radial cull. */
  uint32_t project = 0;     /**< Cycles: gnomonic projection. */
  uint32_t edge_lut = 0;    /**< Cycles: class-LUT bilinear serve. */
  uint32_t edge_convex = 0; /**< Cycles: convex half-plane max. */
  uint32_t edge_sector = 0; /**< Cycles: concave sector walk. */
  uint32_t edge_exact = 0;  /**< Cycles: full per-edge walk. */
  uint32_t pack =
      0; /**< Cycles: plane->angle conversion and result packaging. */
  uint32_t alpha = 0;    /**< Cycles: scan-side AA coverage kernel. */
  uint32_t tick = 0;     /**< Cycles: summed back-to-back counter-read pairs. */
  uint32_t n_probe = 0;  /**< Probes entered. */
  uint32_t n_cull_r = 0; /**< Probes leaving at the radial cull. */
  uint32_t n_lut = 0;    /**< Probes served by the class LUT. */
  uint32_t n_convex = 0; /**< Probes taking the convex path. */
  uint32_t n_sector = 0; /**< Probes taking the sector walk. */
  uint32_t n_exact = 0;  /**< Probes taking the full edge walk. */
  uint32_t n_alpha = 0;  /**< Probes reaching the AA coverage kernel. */
  /** @brief Zeroes every bucket and count. */
  void reset() { *this = {}; }
};
/** @brief Global per-probe cycle buckets (HS_PROBE_BREAKDOWN builds only). */
#ifdef HS_PROBE_BREAKDOWN
inline ProbeBreakdown g_probe_breakdown;
#endif

#ifdef HS_PROFILE_PULLBACK_PROJECTION
/** @brief Per-frame polyhedral reflection counts. */
struct PullbackProjectionCounts {
  uint32_t polyhedral_pixels = 0; /**< Pixels entering polyhedral projection. */
  uint32_t polyhedral_reflections = 0; /**< Reflection iterations executed. */
  uint32_t polyhedral_max_reflections =
      0; /**< Peak reflections for one pixel. */

  /** @brief Zeroes every reflection count. */
  void reset() { *this = {}; }
};

inline PullbackProjectionCounts g_pullback_projection_counts;
#endif

#ifdef HS_PLOT_COUNTS
/** @brief Count-only Plot rasterizer workload attribution. */
struct PlotCounts {
  uint32_t rings = 0;          /**< Paths submitted to `Plot::rasterize()`. */
  uint32_t edges = 0;          /**< Polyline edges submitted. */
  uint32_t planar = 0;         /**< Planar paths submitted. */
  uint32_t geodesic = 0;       /**< Geodesic paths submitted. */
  uint32_t degenerate = 0;     /**< Degenerate paths handled. */
  uint32_t one_dot = 0;        /**< Single-sample paths. */
  uint32_t cull_tests = 0;     /**< Path cull tests. */
  uint32_t culled = 0;         /**< Paths rejected by culling. */
  uint32_t sim_samples = 0;    /**< Samples generated by simulation. */
  uint32_t replay_samples = 0; /**< Samples emitted during replay. */
  uint32_t planar_unprojects = 0;  /**< Planar-to-world conversions. */
  uint32_t planar_arc_samples = 0; /**< Samples on planar arcs. */
  uint32_t normalizations = 0;     /**< Vector normalizations. */
  uint32_t shader_calls = 0;       /**< Fragment-shader invocations. */
  uint32_t plotted_samples = 0;    /**< Samples reaching the framebuffer. */
  uint32_t steps_peak = 0;         /**< Peak cached path steps. */
  uint32_t backstops = 0;          /**< Capacity backstop trips. */

  /** @brief Zeroes every count. */
  void reset() { *this = {}; }
};

inline PlotCounts g_plot_counts;
#endif

#ifdef HS_PROFILE_PLOT_RENDER_COUNTS
/** @brief Count-only attribution for plot rendering. */
struct PlotRenderCounts {
  uint32_t resident_particles = 0; /**< Allocated particle slots. */
  uint32_t live_particles = 0;     /**< Active particles. */
  uint32_t full_histories = 0;     /**< Trails at full history length. */
  uint32_t partial_histories = 0;  /**< Trails still filling. */
  uint32_t draining_histories =
      0; /**< Resident particles with zero remaining life. */
  uint32_t cartesian_latitude_rejects = 0; /**< Latitude-bound rejects. */
  uint32_t cartesian_meridian_rejects = 0; /**< Meridian-bound rejects. */
  uint32_t cartesian_fallbacks = 0;     /**< Cartesian fast-path fallbacks. */
  uint32_t prologue_row_rejects = 0;    /**< Row-bound prologue rejects. */
  uint32_t prologue_column_rejects = 0; /**< Column-bound prologue rejects. */
  uint32_t edge_rejects = 0;            /**< Edges rejected before sampling. */
  uint32_t visible_trails = 0;          /**< Trails reaching rasterization. */
  uint32_t one_dot_edges = 0;           /**< Trails reduced to one sample. */
  uint32_t long_edges = 0;              /**< Trails using adaptive sampling. */
  uint32_t adaptive_samples = 0;        /**< Adaptive samples emitted. */
  uint32_t exact_gate_fallbacks = 0;    /**< Exact visibility fallbacks. */
  uint32_t fragment_shader_calls = 0;   /**< Fragment-shader invocations. */
  uint32_t aa_tap_masks[5]{};           /**< AA masks by populated tap count. */
  uint32_t interior_splats = 0;         /**< Splats wholly inside the clip. */
  uint32_t clip_boundary_splats = 0; /**< Splats crossing the clip boundary. */
  uint32_t palette_endpoints = 0;    /**< Endpoint palette samples. */
  uint32_t palette_interpolated = 0; /**< Interpolated palette samples. */
  uint32_t hole_early_outs = 0;      /**< Hole-mask early exits. */

  /** @brief Zeroes every count. */
  void reset() { *this = {}; }
};

inline PlotRenderCounts g_plot_render_counts;
#endif

#ifdef HS_PROFILE_PLOT_STALLS
#ifndef CORE_TEENSY
#error "HS_PROFILE_PLOT_STALLS requires Teensy DWT registers"
#endif

/** @brief One DWT cycle/stall interval start sample. */
struct DwtStallSample {
  uint32_t cycles;
  uint8_t cpi;
  uint8_t lsu;
  uint8_t exc;
};

inline volatile uint32_t &dwt_cpi_counter() {
  return *reinterpret_cast<volatile uint32_t *>(0xe0001008u);
}

inline volatile uint32_t &dwt_exc_counter() {
  return *reinterpret_cast<volatile uint32_t *>(0xe000100cu);
}

inline volatile uint32_t &dwt_lsu_counter() {
  return *reinterpret_cast<volatile uint32_t *>(0xe0001014u);
}

/** @brief Accumulated short DWT intervals for one pipeline stage. */
struct DwtStallBucket {
  uint64_t cycles = 0;
  uint64_t cpi = 0;
  uint64_t lsu = 0;
  uint64_t exc = 0;
  uint32_t batches = 0;
  uint32_t wrapped = 0;

  /**
   * @brief Adds one interval to the bucket.
   * @param start Sample taken at the interval's start.
   * @details The 8-bit event counters are exact only for intervals shorter
   *          than 256 cycles; a longer interval accumulates truncated and is
   *          tallied in `wrapped`.
   */
  void add(const DwtStallSample &start) {
    const uint32_t span = ARM_DWT_CYCCNT - start.cycles;
    cycles += span;
    cpi += static_cast<uint8_t>(dwt_cpi_counter() - start.cpi);
    lsu += static_cast<uint8_t>(dwt_lsu_counter() - start.lsu);
    exc += static_cast<uint8_t>(dwt_exc_counter() - start.exc);
    if (span >= 256)
      ++wrapped;
    ++batches;
  }

  /** @brief Zeroes every accumulator. */
  void reset() { *this = {}; }
};

/** @brief Plot DWT cycle and stall buckets. */
struct PlotStalls {
  DwtStallBucket history_vertex;      /**< History vertex generation. */
  DwtStallBucket trail_gate;          /**< Trail visibility gate. */
  DwtStallBucket edge_setup;          /**< Edge preparation. */
  DwtStallBucket adaptive_sim;        /**< Adaptive simulation. */
  DwtStallBucket normalized_replay;   /**< Normalized trail replay. */
  DwtStallBucket shade_palette;       /**< Palette lookup and shading. */
  DwtStallBucket projection;          /**< World-to-screen projection. */
  DwtStallBucket aa_weights;          /**< Antialias weight evaluation. */
  DwtStallBucket framebuffer_blend;   /**< Framebuffer blending. */
  DwtStallBucket signed_axis_physics; /**< Signed-axis particle update. */

  /** @brief Zeroes every bucket. */
  void reset() { *this = {}; }
};

inline PlotStalls g_plot_stalls;

/** @brief Enables the Cortex-M7 DWT counters used by stall captures. */
inline void enable_plot_stall_counters() {
  ARM_DEMCR |= ARM_DEMCR_TRCENA;
  ARM_DWT_CTRL |= (1u << 17) | (1u << 18) | (1u << 20) | ARM_DWT_CTRL_CYCCNTENA;
}

/** @brief Reads all four DWT counters at one stage boundary. */
inline DwtStallSample plot_stall_sample() {
  return {ARM_DWT_CYCCNT, static_cast<uint8_t>(dwt_cpi_counter()),
          static_cast<uint8_t>(dwt_lsu_counter()),
          static_cast<uint8_t>(dwt_exc_counter())};
}

/** @brief Explicit two-operation batches for variable-length hot loops. */
class DwtStallBatch {
public:
  explicit DwtStallBatch(DwtStallBucket &target)
      : bucket(target), start(plot_stall_sample()) {}

  /** @brief Closes each full batch and starts the next interval. */
  void step() {
    if (++operations == OPERATIONS_PER_BATCH) {
      bucket.add(start);
      operations = 0;
      start = plot_stall_sample();
    }
  }

  /** @brief Closes the final partial batch; a second call adds nothing. */
  void finish() {
    if (operations != 0) {
      bucket.add(start);
      operations = 0;
    }
  }

  ~DwtStallBatch() { finish(); }
  DwtStallBatch(const DwtStallBatch &) = delete;
  DwtStallBatch &operator=(const DwtStallBatch &) = delete;

private:
  static constexpr uint8_t OPERATIONS_PER_BATCH = 2;
  DwtStallBucket &bucket;
  DwtStallSample start;
  uint8_t operations = 0;
};
#endif

} // namespace hs

// Per-pixel scan instrumentation, compiled in only under HS_SCAN_METRICS.
#ifdef HS_SCAN_METRICS
#define HS_SCAN_METRIC(stmt)                                                   \
  do {                                                                         \
    (stmt);                                                                    \
  } while (0)
#else
#define HS_SCAN_METRIC(stmt) ((void)0)
#endif

// Per-probe stage timing, compiled in only under HS_PROBE_BREAKDOWN.
// HS_PROBE_MARK opens a rolling timestamp; HS_PROBE_SPAN closes one stage and
// reopens the next off the same read.
#ifdef HS_PROBE_BREAKDOWN
#define HS_PROBE_MARK(var) uint32_t var = HS_OS_CYCLES()
#define HS_PROBE_SPAN(field, var)                                              \
  do {                                                                         \
    uint32_t hs_now = HS_OS_CYCLES();                                          \
    hs::g_probe_breakdown.field += hs_now - (var);                             \
    (var) = hs_now;                                                            \
  } while (0)
#define HS_PROBE_COUNT(field)                                                  \
  do {                                                                         \
    ++hs::g_probe_breakdown.field;                                             \
  } while (0)
#define HS_PROBE_TICK()                                                        \
  do {                                                                         \
    uint32_t hs_a = HS_OS_CYCLES();                                            \
    uint32_t hs_b = HS_OS_CYCLES();                                            \
    hs::g_probe_breakdown.tick += hs_b - hs_a;                                 \
  } while (0)
#else
#define HS_PROBE_MARK(var)
#define HS_PROBE_SPAN(field, var) ((void)0)
#define HS_PROBE_COUNT(field) ((void)0)
#define HS_PROBE_TICK() ((void)0)
#endif

#ifdef HS_PROFILE_PULLBACK_PROJECTION
#define HS_PULLBACK_PROJECTION_COUNT(stmt)                                     \
  do {                                                                         \
    (stmt);                                                                    \
  } while (0)
#else
#define HS_PULLBACK_PROJECTION_COUNT(stmt) ((void)0)
#endif

#ifdef HS_PLOT_COUNTS
#define HS_PLOT_COUNT(field) (++hs::g_plot_counts.field)
#define HS_PLOT_ADD(field, value) (hs::g_plot_counts.field += (value))
#define HS_PLOT_MAX(field, value)                                              \
  do {                                                                         \
    uint32_t hs_plot_value = static_cast<uint32_t>(value);                     \
    if (hs_plot_value > hs::g_plot_counts.field)                               \
      hs::g_plot_counts.field = hs_plot_value;                                 \
  } while (0)
#else
#define HS_PLOT_COUNT(field) ((void)0)
#define HS_PLOT_ADD(field, value) ((void)0)
#define HS_PLOT_MAX(field, value) ((void)0)
#endif

#ifdef HS_PROFILE_PLOT_RENDER_COUNTS
#define HS_PLOT_RENDER_COUNT(field) (++hs::g_plot_render_counts.field)
#else
#define HS_PLOT_RENDER_COUNT(field) ((void)0)
#endif

#ifdef HS_PROFILE_PLOT_STALLS
#define HS_PLOT_STALL_START(var)                                               \
  const hs::DwtStallSample var = hs::plot_stall_sample()
#define HS_PLOT_STALL_STOP(field, var) hs::g_plot_stalls.field.add(var)
#else
#define HS_PLOT_STALL_START(var)
#define HS_PLOT_STALL_STOP(field, var) ((void)0)
#endif

#include "platform/cycle_counting.h"
