#pragma once

/**
 * @brief Plots a color to the canvas, ensuring the y-coordinate is within bounds (0 to H-1).
 * * This function serves as a safety check for vertical bounds, plotting only to the
 * physical LED segments (y < H).
 * * @param canvas The canvas object (buffer).
 * @param x The horizontal coordinate (LED index within the buffer, modulo W is often handled upstream).
 * @param y The vertical coordinate (row index).
 * @param c The color (Pixel) to plot.
 */
void plot_virtual(Canvas& canvas, int x, int y, const Pixel& c) {
  if (y >= 0 && y < H) {
    canvas(XY(x, y)) = c;
  }
}

/**
 * @brief Base class for all filters in the rendering pipeline.
 * * Filters form a chain to process pixel data after it is generated by the Effect.
 * It manages the linkage to the next filter and provides core utility methods.
 * * @tparam W The width (number of columns/virtual LEDs) of the effect.
 */
template <int W>
class Filter {
public:
  Filter() : next(nullptr) {}
  virtual ~Filter() = default;

  /**
   * @brief Chains this filter to the next filter in the pipeline.
   * @param filter The next filter object.
   * @return Reference to the next filter object.
   */
  virtual Filter& chain(Filter& filter) {
    next = &filter;
    return filter;
  }

  /**
   * @brief The core plotting function. All derived classes must implement this.
   * * @param canvas The canvas (pixel buffer) to plot onto.
   * @param x The horizontal coordinate (float for sub-pixel accuracy).
   * @param y The vertical coordinate (float for sub-pixel accuracy).
   * @param c The color to plot.
   * @param age The age of the dot/fragment (0.0 for new).
   * @param alpha The opacity/coverage of the fragment.
   */
  virtual void plot(Canvas& canvas, float x, float y,
    const Pixel& c, float age, float alpha) = 0;

  /**
   * @brief Triggers decay logic for filters that manage aging state (e.g., trails).
   */
  virtual void decay() {
    if (next != nullptr) {
      next->decay();
    }
  }

  /**
   * @brief Allows filters to re-plot old state (e.g., trail decay).
   * @param canvas The canvas to plot onto.
   * @param trailFn A function to calculate the color of the aged trail pixel.
   * @param alpha The base opacity/alpha for the trail.
   */
  virtual void trail(Canvas& canvas, TrailFn trailFn, float alpha) {
    if (next != nullptr) {
      next->trail(canvas, trailFn, alpha);
    }
  }

protected:

  /**
   * @brief Passes the processed fragment data to the next filter or the final canvas.
   * @param canvas The current canvas buffer.
   * @param x The processed X coordinate.
   * @param y The processed Y coordinate.
   * @param c The processed color.
   * @param age The age of the fragment.
   * @param alpha The alpha/opacity to blend with.
   */
  void pass(Canvas& canvas, float x, float y,
    const Pixel& c, float age, float alpha)
  {
    if (next == nullptr) {
      auto xi = static_cast<int>(x);
      auto yi = static_cast<int>(y);
      auto p = blend_alpha(alpha)(canvas(xi, yi), c);
      plot_virtual(canvas, xi, yi, p);
    }
    else {
      next->plot(canvas, x, y, c, age, alpha);
    }
  }

  Filter* next; /**< Pointer to the next filter in the chain. */
};

/**
 * @brief A passthrough filter that plots raw pixel data directly.
 * @details Used as the root of the filter chain when no processing is needed.
 * @tparam W The width of the effect.
 */
template <int W>
class FilterRaw : public Filter<W> {
  void plot(Canvas& canvas, float x, float y, const Pixel& c, float age, float alpha) {
    this->pass(canvas, x, y, c, age, alpha);
  }
};

/**
 * @brief Quintic Smootherstep Kernel function (Perlin's 5th order polynomial).
 * @details Guarantees zero velocity and acceleration at t=0 and t=1 for smooth anti-aliasing.
 * @param t The fractional coordinate (0.0 to 1.0).
 * @return The smoothed weight (0.0 to 1.0).
 */
inline float quintic_kernel(float t) {
  t = std::clamp(t, 0.0f, 1.0f);
  // W(t) = 6*t^5 - 15*t^4 + 10*t^3
  return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f);
}

/**
 * @brief A filter implementing anti-aliasing via Quintic Interpolation (Smootherstep).
 * @details Distributes the color/alpha of a sub-pixel position across its four nearest integer pixels
 * using a zero-acceleration weighting curve.
 * @tparam W The width of the effect.
 */
template <int W>
class FilterAntiAlias : public Filter<W> {
public:
  FilterAntiAlias() {}

  void plot(Canvas& canvas, float x, float y, const Pixel& c, float age, float alpha) {
    float x_i = 0;
    float x_m = std::modf(x, &x_i);
    float y_i = 0;
    float y_m = std::modf(y, &y_i);
    float xs = quintic_kernel(x_m);
    float ys = quintic_kernel(y_m);

    float v00 = (1 - xs) * (1 - ys);  // Top-Left weight (xi, yi)
    float v10 = xs * (1 - ys);        // Top-Right weight (xi+1, yi)
    float v01 = (1 - xs) * ys;        // Bottom-Left weight (xi, yi+1)
    float v11 = xs * ys;              // Bottom-Right weight (xi+1, yi+1)

    if (v00 > 0.0001) {
      this->pass(canvas, x_i, y_i, c, age, alpha * v00);
    }
    if (v10 > 0.0001) {
      this->pass(canvas, wrap((x_i + 1), W), y_i, c, age, alpha * v10);
    }
    if (y_i < H - 1) {
      if (v01 > 0.0001) {
        this->pass(canvas, x_i, y_i + 1, c, age, alpha * v01);
      }
      if (v11 > 0.0001) {
        this->pass(canvas, wrap((x_i + 1), W), y_i + 1, c, age, alpha * v11);
      }
    }
  }
};

/**
 * @brief A filter that manages time-to-live (TTL) for fragments, creating trails.
 * * @details Fragments are not passed immediately but tracked internally. On decay,
 * they are plotted as a trail using a color function based on their remaining TTL.
 * * @tparam W The width of the effect.
 * @tparam MAX_PIXELS The maximum number of decaying pixels to track.
 */
template <int W, int MAX_PIXELS>
class FilterDecay : public Filter<W> {
public:

  /**
   * @brief Initializes the filter with a fragment lifetime.
   * @param lifetime The number of frames a trail fragment persists.
   */
  FilterDecay(int lifetime) :
    lifetime(lifetime),
    num_pixels(0)
  {}

  /**
   * @brief Plots a new fragment, optionally tracking it for decay.
   * @details If age >= 0, the fragment is tracked for trails. If age <= 0,
   * it is plotted immediately as a new head.
   */
  void plot(Canvas& canvas, float x, float y, const Pixel& color, float age, float alpha) {
    if (age >= 0) {
      if (num_pixels < MAX_PIXELS) {
        ttls[num_pixels++] = { static_cast<float>(x), static_cast<float>(y), static_cast<float>(lifetime - age) };
      }
      else {
        Serial.println("FilterDecay full!");
      }
    }
    if (age <= 0) {
      this->pass(canvas, x, y, color, age, alpha);
    }
  }

  /**
   * @brief Decrements the TTL of all tracked fragments and removes expired ones.
   */
  void decay() {
    for (int i = 0; i < num_pixels; ++i) {
      if (--ttls[i].ttl < TOLERANCE) {
        num_pixels--;
        if (i < num_pixels) {
          ttls[i] = std::move(ttls[num_pixels]);
          i--;
        }
      }
    }
    Filter<W>::decay();
  }

  /**
   * @brief Re-plots all existing trail fragments with reduced brightness/color based on age.
   * @param canvas The canvas to plot onto.
   * @param trailFn A function to calculate the color based on normalized age (0.0 to 1.0).
   * @param alpha The base opacity for the trails.
   */
  void trail(Canvas& canvas, TrailFn trailFn, float alpha) {
    //    Serial.println(num_pixels);
    for (int i = 0; i < num_pixels; ++i) {
      auto color = trailFn(ttls[i].x, ttls[i].y, 1 - (ttls[i].ttl / lifetime));
      this->pass(canvas, ttls[i].x, ttls[i].y, color, lifetime - ttls[i].ttl, alpha);
    }
    Filter<W>::trail(canvas, trailFn, alpha);
  }

private:

  /**
   * @brief Structure holding the state of a single decaying pixel fragment.
   */
  struct DecayPixel {
    float x; /**< X coordinate. */
    float y; /**< Y coordinate. */
    float ttl; /**< Time to Live (remaining frames). */
  };

  int lifetime; /**< The initial lifetime for a fragment. */
  std::array<DecayPixel, MAX_PIXELS> ttls; /**< Array of tracked decay pixels. */
  int num_pixels; /**< The current number of active decay pixels. */
};

/**
 * @brief A filter that shifts the RGB channels slightly to create a chromatic aberration effect.
 * @tparam W The width of the effect.
 */
template<int W>
class FilterChromaticShift : public Filter<W> {
public:

  FilterChromaticShift()
  {
  }

  /**
   * @brief Plots the original color, then plots R, G, and B components at slightly offset positions.
   */
  void plot(Canvas& canvas, float x, float y, const Pixel& color, float age, float alpha) {
    CRGB r(color.r, 0, 0);
    CRGB g(0, color.g, 0);
    CRGB b(0, 0, color.b);
    this->pass(canvas, x, y, color, age, alpha);
    this->pass(canvas, wrap(x + 0.66f, W), y, r, age, alpha);
    this->pass(canvas, wrap(x + 1.33f, W), y, g, age, alpha);
    this->pass(canvas, wrap(x + 2.0f, W), y, b, age, alpha);
    /*
        this->pass(canvas, wrap(x - 0.66f, W), y, r, age, alpha);
        this->pass(canvas, wrap(x - 1.33f, W), y, g, age, alpha);
        this->pass(canvas, wrap(x - 2.0f, W), y, b, age, alpha);
        */
  }
};

/**
 * @brief A filter that applies the current global orientation to the pixel position.
 * @details Necessary for effects that rotate the entire scene. Converts the 2D pixel to a 3D vector,
 * rotates it by the Orientation quaternion, and re-projects it to 2D.
 * @tparam W The width of the effect.
 */
template <int W>
class FilterOrient : public Filter<W> {
public:
  /**
   * @brief Initializes the filter with a reference to the global orientation state.
   * @param orientation Reference to the Orientation object.
   */
  FilterOrient(Orientation& orientation) :
    orientation(orientation)
  {}

  /**
   * @brief Rotates the pixel's 3D position based on the current orientation.
   */
  void plot(Canvas& canvas, float x, float y, const Pixel& color, float age, float alpha) {
    auto v = pixel_to_vector<W>(x, y);
    auto r = vector_to_pixel<W>(orientation.orient(v));
    this->pass(canvas, r.x, r.y, color, age, alpha);
  }

private:

  Orientation& orientation; /**< Reference to the global Orientation state. */
};

/**
 * @brief A filter that replicates the plotted pixel horizontally multiple times.
 * @details Used for visual effects like simulating multiple light sources or widening a sparse plot.
 * @tparam W The width of the effect.
 */
template <int W>
class FilterReplicate : public Filter<W> {
public:

  /**
   * @brief Initializes the filter with the number of times to replicate.
   * @param count The number of copies to create horizontally. Clamped between 1 and W.
   */
  FilterReplicate(int count) :
    count(std::clamp(count, 1, W))
  {}

  /**
   * @brief Plots the fragment at its original position and at evenly spaced offsets.
   */
  void plot(Canvas& canvas, float x, float y, const Pixel& color, float age, float alpha) {
    for (int i = 0; i < W; i += W / count) {
      this->pass(canvas, wrap(x + i, W), y, color, age, alpha);
    }
  }

private:

  int count; /**< The number of times to replicate the pixel. */
};