# Expand module-owned section headers for the roster and case-call gates.

function(hs_read_test_header path output)
  file(READ "${path}" _text)
  get_filename_component(_module "${path}" NAME_WE)
  string(REGEX REPLACE "^test_" "" _module "${_module}")
  string(REGEX MATCHALL "#include \"tests/[A-Za-z0-9_]+/[A-Za-z0-9_]+\\.h\""
    _includes "${_text}")
  foreach(_include IN LISTS _includes)
    string(REGEX REPLACE "^#include \"tests/(.*)\"$" "\\1" _part "${_include}")
    if(NOT _part MATCHES "^${_module}/[A-Za-z0-9_]+\\.h$")
      message(FATAL_ERROR "${path}: section header belongs to another module: ${_part}")
    endif()
    file(READ "${TESTS_DIR}/${_part}" _body)
    string(REPLACE "${_include}" "\n${_body}\n" _text "${_text}")
  endforeach()
  set(${output} "${_text}" PARENT_SCOPE)
endfunction()

function(hs_check_test_sections)
  file(GLOB_RECURSE _parts RELATIVE "${TESTS_DIR}" "${TESTS_DIR}/*/*.h")
  foreach(_part IN LISTS _parts)
    if(NOT _part MATCHES "^([A-Za-z0-9_]+)/[A-Za-z0-9_]+\\.h$")
      message(FATAL_ERROR "invalid test section header path: ${_part}")
    endif()
    set(_owner "${TESTS_DIR}/test_${CMAKE_MATCH_1}.h")
    if(NOT EXISTS "${_owner}")
      message(FATAL_ERROR "${_part}: missing owner ${_owner}")
    endif()
    get_filename_component(_root "${TESTS_DIR}" DIRECTORY)
    if(EXISTS "${_root}/core/${_part}" OR EXISTS "${_root}/${_part}")
      message(FATAL_ERROR "${_part}: section header shadows an engine include")
    endif()
    file(READ "${_owner}" _text)
    string(REGEX REPLACE "/\\*[^*]*\\*+([^/*][^*]*\\*+)*/" "\n" _text "${_text}")
    string(REGEX REPLACE "//[^\n]*" "" _text "${_text}")
    string(REGEX MATCHALL "#include \"tests/${_part}\"" _includes "${_text}")
    list(LENGTH _includes _count)
    if(NOT _count EQUAL 1)
      message(FATAL_ERROR "${_part}: owner must include its section once; found ${_count}")
    endif()
  endforeach()
endfunction()
