// Emits core/color/srgb_decode_lut.h: the 8 KB split-decode table for
// linear16->sRGB8, derived from the exact linear_to_srgb_lut. Asserts every
// 16-wide bucket holds <=1 output step and self-verifies bit-exactness over all
// 65536 inputs. Build: clang++ -std=c++20 -I. -Icore scripts/generate_srgb_decode.cpp
// (unit_srgb_decode re-checks the equivalence in CI).
#include "core/color/color_luts.h"
#include <cstdint>
#include <cstdio>

int main() {
  static uint16_t
      packed[4096]; // low byte = base output, high byte = step point
  int max_steps = 0;
  for (int hi = 0; hi < 4096; ++hi) {
    int base = linear_to_srgb_lut[hi * 16];
    int thresh = 16; // sentinel: no step in this bucket
    int steps = 0;
    int cur = base;
    for (int lo = 1; lo < 16; ++lo) {
      int val = linear_to_srgb_lut[hi * 16 + lo];
      if (val != cur) {
        ++steps;
        if (val == base + 1 && thresh == 16)
          thresh = lo;
        cur = val;
      }
    }
    if (steps > max_steps)
      max_steps = steps;
    if (steps > 1) {
      std::printf(
          "FAIL: bucket %d has %d steps (>1); 16-wide bucketing invalid\n", hi,
          steps);
      return 1;
    }
    packed[hi] = (uint16_t)((thresh << 8) | (base & 0xFF));
  }
  // Exhaustive bit-exact check against the source LUT.
  long mism = 0;
  for (int v = 0; v < 65536; ++v) {
    uint16_t e = packed[v >> 4];
    int out = (e & 0xFF) + (((v & 0xF) >= (e >> 8)) ? 1 : 0);
    if (out != linear_to_srgb_lut[v]) {
      if (mism < 10)
        std::printf("MISMATCH v=%d decode=%d lut=%d\n", v, out,
                    linear_to_srgb_lut[v]);
      ++mism;
    }
  }
  std::printf("max_steps_per_bucket=%d  mismatches=%ld / 65536\n", max_steps,
              mism);
  if (mism)
    return 1;
  // Emit the header.
  FILE *f = std::fopen("core/color/srgb_decode_lut.h", "w");
  std::fprintf(f, "#pragma once\n#include \"engine/platform.h\"\n");
  std::fprintf(f, "// Generated by scripts/generate_srgb_decode.cpp from "
                  "linear_to_srgb_lut.\n");
  std::fprintf(
      f,
      "// Split-decode of linear16->sRGB8: 16-wide buckets, each <=1 step.\n");
  std::fprintf(
      f,
      "// Entry: low byte = base output, high byte = step point in [0,16].\n");
  std::fprintf(f, "// clang-format off\n");
  std::fprintf(f, "inline const uint16_t srgb_decode_lut[4096] PROGMEM = {\n");
  for (int i = 0; i < 4096; ++i) {
    if (i % 12 == 0)
      std::fprintf(f, "    ");
    std::fprintf(f, "0x%04x,", packed[i]);
    std::fprintf(f, (i % 12 == 11) ? "\n" : " ");
  }
  std::fprintf(f, "\n};\n");
  std::fclose(f);
  std::printf("wrote core/color/srgb_decode_lut.h\n");
  return 0;
}
