// Emits core/color/srgb_decode_lut.h: the two-region split-decode tables for
// linear16->sRGB8, derived from the exact linear_to_srgb_lut. A fine 16-wide
// low region [0, SRGB_DECODE_VSPLIT) and a coarse 128-wide high region up to
// 65536, each bucket holding <=1 output step, so the decode is a single
// branchless compare per region. Asserts the <=1-step property and self-
// verifies bit-exactness over all 65536 inputs. Total ~1.5 KB (fits the DTCM
// slack). Widening a region invalidates the committed table, so the length
// static_asserts in srgb_decode.h must be relaxed to rebuild this.
// Build: clang++ -std=c++20 -I. -Icore scripts/generate_srgb_decode.cpp
// Run from the repo root; argv[1] overrides the output path (CI writes to a
// temp file and diffs it against the committed header).
// (unit_color's test_linear_to_srgb8_decode_matches_lut re-checks the
// equivalence in CI).
#include "core/color/color_luts.h"
#include "core/color/srgb_decode.h"
#include <cstdint>
#include <cstdio>

// Bucket geometry (SRGB_DECODE_*) and the decode itself come from
// core/color/srgb_decode.h: the verification below runs the shipping
// linear_to_srgb8 over the freshly packed tables, not a second copy of it.

// Pack one bucket [base_v, base_v+width) into (step<<8)|base; step is the
// offset in [0,width] where the output increments (== width if constant).
// Returns false if the bucket holds more than one step (bucketing too coarse).
static bool pack_bucket(int base_v, int width, uint16_t &out) {
  int base = linear_to_srgb_lut[base_v];
  int step = width, seen = 0, cur = base;
  for (int k = 1; k < width && base_v + k < 65536; ++k) {
    int val = linear_to_srgb_lut[base_v + k];
    if (val != cur) {
      if (++seen > 1)
        return false;
      if (val == base + 1)
        step = k;
      cur = val;
    }
  }
  out = (uint16_t)((step << 8) | (base & 0xFF));
  return true;
}

int main(int argc, char **argv) {
  const char *out_path = argc > 1 ? argv[1] : "core/color/srgb_decode_lut.h";
  static uint16_t low[SRGB_DECODE_LOW_N], high[SRGB_DECODE_HIGH_N];
  for (int i = 0; i < SRGB_DECODE_LOW_N; ++i)
    if (!pack_bucket(i << SRGB_DECODE_LOW_SHIFT, 1 << SRGB_DECODE_LOW_SHIFT,
                     low[i])) {
      std::printf("FAIL: low bucket %d has >1 step\n", i);
      return 1;
    }
  for (int i = 0; i < SRGB_DECODE_HIGH_N; ++i)
    if (!pack_bucket(SRGB_DECODE_VSPLIT + (i << SRGB_DECODE_HIGH_SHIFT),
                     1 << SRGB_DECODE_HIGH_SHIFT, high[i])) {
      std::printf("FAIL: high bucket %d has >1 step\n", i);
      return 1;
    }
  // Point the runtime tables at what was just packed, then verify through the
  // shipping decode.
  for (int i = 0; i < SRGB_DECODE_LOW_N; ++i)
    srgb_decode_low[i] = low[i];
  for (int i = 0; i < SRGB_DECODE_HIGH_N; ++i)
    srgb_decode_high[i] = high[i];
  long mism = 0;
  for (int v = 0; v < 65536; ++v)
    if (linear_to_srgb8((uint16_t)v) != linear_to_srgb_lut[v])
      ++mism;
  std::printf("low=%d high=%d bytes=%d  mismatches=%ld / 65536\n",
              SRGB_DECODE_LOW_N, SRGB_DECODE_HIGH_N,
              (SRGB_DECODE_LOW_N + SRGB_DECODE_HIGH_N) * 2, mism);
  if (mism)
    return 1;

    // Binary mode: the committed header is LF on every host (.gitattributes),
    // and text mode would emit CRLF on Windows. The Windows CRT deprecates fopen
    // in favour of fopen_s, which no other host provides.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
  FILE *f = std::fopen(out_path, "wb");
#pragma clang diagnostic pop
  if (!f) {
    std::perror(out_path);
    std::printf("FAIL: open %s\n", out_path);
    return 1;
  }
  std::fprintf(f, "/*\n"
                  " * Required Notice: Copyright 2025 Gabriel Levy. All rights "
                  "reserved.\n"
                  " * Licensed under the PolyForm Noncommercial License 1.0.0\n"
                  " */\n");
  std::fprintf(f, "#pragma once\n#include \"engine/platform.h\"\n");
  std::fprintf(f, "// Generated by scripts/generate_srgb_decode.cpp from "
                  "linear_to_srgb_lut.\n// Do not edit.\n");
  std::fprintf(f,
               "// Two-region split-decode of linear16->sRGB8: %d-wide low "
               "[0,%d), %d-wide high.\n",
               1 << SRGB_DECODE_LOW_SHIFT, SRGB_DECODE_VSPLIT,
               1 << SRGB_DECODE_HIGH_SHIFT);
  std::fprintf(f,
               "// Entry: low byte = base output, high byte = step point.\n");
  std::fprintf(f, "inline constexpr int SRGB_DECODE_VSPLIT = %d;\n",
               SRGB_DECODE_VSPLIT);
  auto emit = [&](const char *name, const uint16_t *t, int n) {
    std::fprintf(f, "// clang-format off\n");
    std::fprintf(f, "inline constexpr uint16_t %s[%d] PROGMEM = {\n", name, n);
    for (int i = 0; i < n; ++i) {
      if (i % 12 == 0)
        std::fprintf(f, "    ");
      std::fprintf(f, "0x%04x,", t[i]);
      std::fprintf(f, (i % 12 == 11) ? "\n" : " ");
    }
    std::fprintf(f, "\n};\n// clang-format on\n");
  };
  emit("srgb_decode_low_src", low, SRGB_DECODE_LOW_N);
  emit("srgb_decode_high_src", high, SRGB_DECODE_HIGH_N);
  const bool write_failed = std::ferror(f) != 0;
  if (std::fclose(f) != 0 || write_failed) {
    std::perror(out_path);
    std::printf("FAIL: write %s\n", out_path);
    return 1;
  }
  std::printf("wrote %s\n", out_path);
  return 0;
}
