#!/usr/bin/env python3
"""Regenerate core/color/color_luts.h — the sRGB transfer-function lookup tables.

The forward table maps 8-bit sRGB to the engine's 16-bit linear working space
in one load. The reverse table is the exact linear -> sRGB reference; the
runtime encode path is core/color/srgb_decode.h. Both mirror the reference
implementations in core/color/color_space.h:

  srgb_to_linear(s) = s/12.92                       if s <= 0.04045
                      ((s+0.055)/1.055) ** 2.4       otherwise
  linear_to_srgb(l) = l*12.92                        if l <= 0.0031308
                      1.055 * l**(1/2.4) - 0.055      otherwise

quantized by round(clamp(v,0,1) * max), i.e. the +0.5 rule the C++
float_to_pixel16 / CRGB byte conversions use:

  srgb_to_linear_lut[256]    : sRGB byte i  -> round(srgb_to_linear(i/255)   * 65535)
  linear_to_srgb_lut[65536]  : linear u16 i -> round(linear_to_srgb(i/65535) * 255)

Precision note: the checked-in tables were generated in IEEE double precision and
reproduce bit-for-bit only in doubles — Python's native float (and numpy float64)
is correct; computing in float32 flips one srgb_to_linear entry at an LSB
rounding boundary.

Usage:
  python scripts/generate_luts.py -o core/color/color_luts.h

Output is piped through clang-format with the repo .clang-format (CLANG_FORMAT
overrides the binary). The generator exits without emitting when clang-format
is missing or its major version is not EXPECTED_CLANG_FORMAT_MAJOR.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from io import StringIO
from pathlib import Path


def srgb_to_linear(s):
    return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4


def linear_to_srgb(lin):
    return lin * 12.92 if lin <= 0.0031308 else 1.055 * lin ** (1.0 / 2.4) - 0.055


# Axis sizes and quantization maxima.
SRGB_LEVELS = 256
LINEAR_LEVELS = 65536
SRGB_MAX = SRGB_LEVELS - 1
LINEAR_MAX = LINEAR_LEVELS - 1


# The clang-format major the CI provenance gate formats with; another major
# reflows the arrays.
EXPECTED_CLANG_FORMAT_MAJOR = 22


def quantize(v, max_val):
    return int(min(max(v, 0.0), 1.0) * max_val + 0.5)


def srgb_to_linear_lut():
    return [quantize(srgb_to_linear(i / SRGB_MAX), LINEAR_MAX) for i in range(SRGB_LEVELS)]


def linear_to_srgb_lut():
    return [quantize(linear_to_srgb(i / LINEAR_MAX), SRGB_MAX) for i in range(LINEAR_LEVELS)]


def emit_array(out, decl, values, per_row):
    out.write(decl + " = {\n")
    for start in range(0, len(values), per_row):
        row = values[start:start + per_row]
        out.write("    " + ", ".join(str(v) for v in row) + ",\n")
    out.write("};\n")


def render(out, fwd, rev):
    out.write("/*\n")
    out.write(" * Required Notice: Copyright 2025 Gabriel Levy."
              " All rights reserved.\n")
    out.write(" * Licensed under the PolyForm Noncommercial License 1.0.0\n")
    out.write(" */\n")
    out.write("#pragma once\n")
    out.write('#include "platform/platform.h"\n')
    out.write("// Generated by scripts/generate_luts.py. Do not edit.\n")
    out.write("// sRGB transfer-function LUTs for color conversion.\n")
    out.write("\n")
    out.write("// sRGB (0-255) -> Linear (0-65535)\n")
    # per_row only shapes the pre-format text; clang-format repacks the rows.
    emit_array(out, f"inline const uint16_t srgb_to_linear_lut[{SRGB_LEVELS}] HS_PROGMEM_UNIQUE(srgb_to_linear_lut)",
               fwd, 11)
    out.write("\n")
    out.write("#if HS_ENABLE_TEST_ORACLES\n")
    out.write("// Linear (0-65535) -> sRGB (0-255)\n")
    out.write("// Reference table only; the runtime encode path is"
              " core/color/srgb_decode.h.\n")
    emit_array(out, f"inline const uint8_t linear_to_srgb_lut[{LINEAR_LEVELS}] HS_PROGMEM_UNIQUE(linear_to_srgb_lut)",
               rev, 15)
    out.write("#endif\n")


def clang_format_major(cf):
    """Major version of the clang-format at `cf`, or None if it cannot be read.

    A missing binary, nonzero exit or unrecognized banner returns None.
    """
    try:
        result = subprocess.run([cf, "--version"], capture_output=True, text=True)
    except OSError:
        return None
    if result.returncode != 0:
        return None
    m = re.search(r"version (\d+)\.", result.stdout)
    return int(m.group(1)) if m else None


def require_format_version(cf):
    major = clang_format_major(cf)
    if major != EXPECTED_CLANG_FORMAT_MAJOR:
        sys.stderr.write(
            f"generate_luts: clang-format-{EXPECTED_CLANG_FORMAT_MAJOR} required; "
            f"found {major if major is not None else 'unknown'} at {cf}\n"
            "Check the CLANG_FORMAT override.\n")
        sys.exit(1)


def clang_format(text):
    """Format the generated header through clang-format using the repo style.

    Returns the formatted text, or None if clang-format is unavailable. Exits
    non-zero if clang-format is present but fails. --assume-filename makes it
    find the repo .clang-format and select C++.
    """
    cf = os.environ.get("CLANG_FORMAT") or shutil.which("clang-format")
    if not cf:
        return None
    require_format_version(cf)
    header = Path(__file__).resolve().parent.parent / "core" / "color" / "color_luts.h"
    result = subprocess.run(
        [cf, "--assume-filename=" + str(header)],
        input=text, capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write("generate_luts: clang-format failed:\n" + result.stderr)
        sys.exit(1)
    return result.stdout


def check(fwd, rev):
    """Self-validate the tables: monotonicity and round-trip fidelity.

    Both tables must be monotonic non-decreasing. The sRGB round trip
    (byte -> linear -> byte) must return the exact input code. Returns the
    number of failures (0 == pass).
    """
    fails = 0
    for name, table in (("srgb_to_linear_lut", fwd), ("linear_to_srgb_lut", rev)):
        for i in range(1, len(table)):
            if table[i] < table[i - 1]:
                sys.stderr.write(
                    f"generate_luts: {name} not monotonic at {i}: "
                    f"{table[i - 1]} -> {table[i]}\n")
                fails += 1
    for s in range(SRGB_LEVELS):
        rt = rev[fwd[s]]
        if rt != s:
            sys.stderr.write(
                f"generate_luts: round trip {s} -> {fwd[s]} -> {rt} "
                f"is not exact\n")
            fails += 1
    return fails


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="run the table self-test only; emit no header")
    parser.add_argument("-o", "--output", help="write the header as UTF-8 with LF newlines")
    args = parser.parse_args()
    fwd = srgb_to_linear_lut()
    rev = linear_to_srgb_lut()
    if args.check:
        sys.exit(1 if check(fwd, rev) else 0)
    if check(fwd, rev):
        sys.stderr.write("generate_luts: self-test failed; refusing to emit\n")
        sys.exit(1)
    # LF on every host: the committed header is LF-pinned.
    sys.stdout.reconfigure(newline="\n")
    buf = StringIO()
    render(buf, fwd, rev)
    text = buf.getvalue()
    formatted = clang_format(text)
    if formatted is None:
        sys.stderr.write(
            "generate_luts: clang-format not found; refusing to emit. "
            "Set CLANG_FORMAT to the binary path.\n")
        sys.exit(1)
    else:
        if args.output:
            with open(args.output, "w", encoding="utf-8", newline="\n") as output:
                output.write(formatted)
        else:
            sys.stdout.write(formatted)


if __name__ == "__main__":
    main()
