#!/usr/bin/env python3
"""Report tracked edits except reproducible documentation generated by the build."""

from __future__ import annotations

import argparse
import contextlib
import io
import subprocess
from pathlib import Path, PurePosixPath

import docs_check
import docs_sync


def changed_sources(root: Path) -> list[str]:
    changed = subprocess.check_output(
        ["git", "-C", str(root), "diff", "HEAD", "--name-only", "-z"],
        timeout=30).decode("utf-8").split("\0")
    changed = [name for name in changed if name]
    if not changed or any(not name.endswith(".md") for name in changed):
        return changed

    with contextlib.redirect_stdout(io.StringIO()):
        _, entries = docs_check.tracked_entries(root)
        checkout = docs_sync.discover_daydream(root)
        roots = {"daydream": checkout} if checkout else {}
        revisions = docs_sync.checkout_revisions(roots)
        checkouts = {name: docs_check.tracked_entries(path, revisions[name])[1]
                     for name, path in roots.items()}
        counts = docs_sync.source_counts(root)
        dirty = []
        for name in changed:
            original = subprocess.run(
                ["git", "-C", str(root), "show", f"HEAD:{name}"],
                capture_output=True, timeout=30)
            path = root / name
            if original.returncode or not path.is_file():
                dirty.append(name)
                continue
            expected = docs_sync.sync_text(
                PurePosixPath(name), original.stdout.decode("utf-8-sig"),
                entries, checkouts, counts)
            if path.read_text(encoding="utf-8-sig") != expected:
                dirty.append(name)
        return dirty


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    try:
        changed = changed_sources(args.root.resolve())
    except (OSError, UnicodeError, ValueError, subprocess.SubprocessError) as error:
        print(f"Cannot determine engine source state: {error}")
        return 1
    if changed:
        print("\n".join(changed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
