/*
 * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.
 * Licensed under the PolyForm Noncommercial License 1.0.0
 */

#include "core/engine/engine.h"

#include <cstdio>
#include <fstream>

namespace {

// Budget: PALETTE_COUNT * LUT_SIZE * sizeof(Pixel) = 393,216 B of flash, about
// a fifth of the Teensy flash budget in tools/teensy_budgets.json, and the same
// again in the WASM data segment. Raising either dimension is a size-gate
// decision, not a cosmetic one.
constexpr int PALETTE_COUNT = 256;
constexpr int LUT_SIZE = 256;

PaletteRecipe make_recipe(float base_turns) {
  PaletteRecipe recipe;
  recipe.schema_version = PaletteRecipe::SCHEMA_VERSION;
  recipe.input.offset = 0.0f;
  recipe.input.span = 0.624f;
  recipe.domain = PaletteDomain::STRAIGHT;
  recipe.easing = SegmentEase::COSINE;
  recipe.color_path = ColorPath::OKLAB_CARTESIAN;
  recipe.hue.mode = HueMode::HARMONY;
  recipe.hue.harmony = PaletteHarmony::TRIADIC;
  recipe.hue.direction = HueDirection::CLOCKWISE;
  recipe.hue.base_turns = base_turns;
  recipe.hue.spread_turns = 0.07f;
  recipe.hue.sweep_turns = 1.0f;
  recipe.hue.custom_turns = {0.0f, 0.0f, 0.0f, 0.0f};
  recipe.lightness.curve = AxisCurve::DESCENDING;
  recipe.lightness.center = 0.37f;
  recipe.lightness.range = 0.5f;
  recipe.lightness.custom = {0.0f, 0.0f, 0.0f, 0.0f};
  recipe.chroma.curve = AxisCurve::CONSTANT;
  recipe.chroma.basis = ChromaBasis::LOCAL_GAMUT;
  recipe.chroma.center = 0.95f;
  recipe.chroma.range = 0.0f;
  recipe.chroma.headroom = 0.94f;
  recipe.chroma.custom = {0.0f, 0.0f, 0.0f, 0.0f};
  recipe.hue_torsion = 0.0f;
  recipe.falloff_start = 0.9f;
  return recipe;
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: mindsplatter_palette_gen <output-header>\n");
    return 2;
  }

  std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
  if (!out) {
    std::fprintf(stderr, "cannot open %s\n", argv[1]);
    return 1;
  }

  out << "/*\n"
         " * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.\n"
         " * Licensed under the PolyForm Noncommercial License 1.0.0\n"
         " * Generated by tools/mindsplatter_palette_gen.cpp.\n"
         " */\n"
         "#pragma once\n\n"
         "#include \"core/color/color.h\"\n\n"
         "inline constexpr int MINDSPLATTER_PALETTE_COUNT = 256;\n"
         "inline constexpr int MINDSPLATTER_PALETTE_LUT_SIZE = 256;\n\n"
         "// clang-format off\n"
         "inline const Pixel MINDSPLATTER_PALETTES"
         "[MINDSPLATTER_PALETTE_COUNT][MINDSPLATTER_PALETTE_LUT_SIZE] "
         "HS_PROGMEM_UNIQUE(MINDSPLATTER_PALETTES) = {\n";

  for (int hue = 0; hue < PALETTE_COUNT; ++hue) {
    const PaletteRecipe recipe =
        make_recipe(0.08611111f + static_cast<float>(hue) / PALETTE_COUNT);
    GenerativePalette palette;
    PaletteRecipe canonical;
    PaletteCompileStatus status;
    if (!GenerativePalette::try_compile(recipe, palette, canonical, status)) {
      std::fprintf(stderr, "palette %d: recipe error %d at field %d\n", hue,
                   static_cast<int>(status.code),
                   static_cast<int>(status.field));
      return 1;
    }
    out << "    {";
    for (int index = 0; index < LUT_SIZE; ++index) {
      const Pixel color =
          palette.get(static_cast<float>(index) / (LUT_SIZE - 1)).color;
      if (index)
        out << ", ";
      out << "Pixel(" << color.r << ", " << color.g << ", " << color.b << ")";
    }
    out << "},\n";
  }
  out << "};\n"
         "// clang-format on\n\n"
         "static_assert(sizeof(MINDSPLATTER_PALETTES) == 256 * 256 * "
         "sizeof(Pixel));\n";
  return 0;
}
