/*
 * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.
 * Licensed under the PolyForm Noncommercial License 1.0.0
 */

#include "core/color/effect_palette_recipes.h"
#include "core/engine/engine.h"

#include <cstdio>
#include <fstream>

namespace {

// Budget: PALETTE_COUNT * LUT_SIZE * sizeof(Pixel) = 393,216 B of flash, about
// a fifth of the Teensy flash budget in tools/teensy_budgets.json, and the same
// again in the WASM data segment. Raising either dimension is a size-gate
// decision, not a cosmetic one.
constexpr int PALETTE_COUNT = 256;
constexpr int LUT_SIZE = 256;

} // namespace

int main(int argc, char **argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: mindsplatter_palette_gen <output-header>\n");
    return 2;
  }

  std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
  if (!out) {
    std::fprintf(stderr, "cannot open %s\n", argv[1]);
    return 1;
  }

  out << "/*\n"
         " * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.\n"
         " * Licensed under the PolyForm Noncommercial License 1.0.0\n"
         " * Generated by tools/mindsplatter_palette_gen.cpp.\n"
         " * DO NOT EDIT. Regenerate with:\n"
         " *   cmake --build --preset tests --target "
         "regenerate_mindsplatter_palette\n"
         " *\n"
         " * MindSplatter's trail palette bank: one 256-entry triadic LUT per\n"
         " * base hue, compiled from EffectPaletteRecipes::mind_splatter.\n"
         " */\n"
         "#pragma once\n\n"
         "#include \"color/color.h\"\n\n"
      << "inline constexpr int MINDSPLATTER_PALETTE_COUNT = " << PALETTE_COUNT
      << ";\n"
         "inline constexpr int MINDSPLATTER_PALETTE_LUT_SIZE = "
      << LUT_SIZE
      << ";\n\n"
         "// clang-format off\n"
         "inline const Pixel MINDSPLATTER_PALETTES"
         "[MINDSPLATTER_PALETTE_COUNT][MINDSPLATTER_PALETTE_LUT_SIZE] "
         "HS_PROGMEM_UNIQUE(MINDSPLATTER_PALETTES) = {\n";

  for (int hue = 0; hue < PALETTE_COUNT; ++hue) {
    const PaletteRecipe recipe = EffectPaletteRecipes::mind_splatter(
        EffectPaletteRecipes::mind_splatter_bank_turns(hue, PALETTE_COUNT));
    GenerativePalette palette;
    PaletteRecipe canonical;
    PaletteCompileStatus status;
    if (!GenerativePalette::try_compile(recipe, palette, canonical, status)) {
      std::fprintf(stderr, "palette %d: recipe error %d at field %d\n", hue,
                   static_cast<int>(status.code),
                   static_cast<int>(status.field));
      return 1;
    }
    out << "    {";
    for (int index = 0; index < LUT_SIZE; ++index) {
      const Pixel color =
          palette.get(static_cast<float>(index) / (LUT_SIZE - 1)).color;
      if (index)
        out << ", ";
      out << "Pixel(" << color.r << ", " << color.g << ", " << color.b << ")";
    }
    out << "},\n";
  }
  out << "};\n"
         "// clang-format on\n\n"
         "static_assert(sizeof(MINDSPLATTER_PALETTES) == "
      << PALETTE_COUNT << " * " << LUT_SIZE << " * sizeof(Pixel));\n";

  // Closed explicitly: the destructor's flush swallows its own failure, and a
  // short write would leave a truncated header behind an exit status of 0.
  out.close();
  if (!out) {
    std::fprintf(stderr, "cannot write %s\n", argv[1]);
    return 1;
  }
  return 0;
}
