/*
 * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.
 * Licensed under the Polyform Noncommercial License 1.0.0
 */

#include "core/engine/memory.h"
#include "tools/mindsplatter_whitebox.h"

#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iomanip>
#include <string>
#include <vector>

namespace {

constexpr int WIDTH = 288;
constexpr int HEIGHT = 144;
constexpr int WARMUP_FRAMES = 136;
constexpr unsigned long FRAME_MS = 16;
constexpr unsigned long FRAME_US = 16000;
constexpr const char *CORPUS_ID = "dense_preset0_f136";
constexpr const char *SOURCE_ID = "mindsplatter_replay_gen seed=1337 preset=0 "
                                  "warmup=136 compiler=" __VERSION__;

using ReplayEffect = MindSplatter<WIDTH, HEIGHT>;
using WhiteBox = hs_test::effects_tests::MindSplatterWhiteBox;

uint64_t fnv1a(uint64_t hash, uint8_t byte) {
  return (hash ^ byte) * 1099511628211ull;
}

template <typename T>
void emit_array(std::ostream &out, const char *type, const char *name,
                const std::vector<T> &values, int columns) {
  out << "inline const " << type << ' ' << name << "[] PROGMEM = {\n";
  for (size_t i = 0; i < values.size(); ++i) {
    if (i % columns == 0)
      out << "    ";
    out << static_cast<uint64_t>(values[i]) << ',';
    if (i % columns == static_cast<size_t>(columns - 1) ||
        i + 1 == values.size())
      out << '\n';
    else
      out << ' ';
  }
  out << "};\n\n";
}

struct GoldenPixel {
  uint16_t index;
  uint16_t r;
  uint16_t g;
  uint16_t b;
};

void emit_golden(std::ostream &out, const std::vector<GoldenPixel> &pixels) {
  out << "inline const GoldenPixel DENSE_PRESET0_F136_FRAMEBUFFER[] PROGMEM = "
         "{\n";
  for (const GoldenPixel &pixel : pixels)
    out << "    {" << pixel.index << ", " << pixel.r << ", " << pixel.g << ", "
        << pixel.b << "},\n";
  out << "};\n\n";
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 2) {
    std::fprintf(stderr, "usage: mindsplatter_replay_gen <output-header>\n");
    return 2;
  }

  GenerativePalette::reset_hue_seed(0);
  hs::random().seed(1337u);
  hs::set_mock_time(0, 0);
  configure_arenas_default();
  ReplayEffect effect;
  effect.init();
  for (int frame = 0; frame < WARMUP_FRAMES; ++frame) {
    hs::set_mock_time(static_cast<unsigned long>(frame) * FRAME_MS,
                      static_cast<unsigned long>(frame) * FRAME_US);
    effect.draw_frame();
    effect.advance_display();
  }

  const auto snapshot = WhiteBox::capture(effect);
  const std::vector<unsigned char> state = WhiteBox::serialize_render(snapshot);
  WhiteBox::draw_particles(effect);
  effect.advance_display();
  const Pixel *pixels = effect.display_buffer();
  std::vector<uint16_t> framebuffer;
  framebuffer.reserve(static_cast<size_t>(WIDTH) * HEIGHT * 3);
  std::vector<GoldenPixel> golden;
  uint64_t framebuffer_hash = 1469598103934665603ull;
  for (int i = 0; i < WIDTH * HEIGHT; ++i) {
    if (pixels[i].r | pixels[i].g | pixels[i].b)
      golden.push_back(
          {static_cast<uint16_t>(i), pixels[i].r, pixels[i].g, pixels[i].b});
    for (uint16_t channel : {pixels[i].r, pixels[i].g, pixels[i].b}) {
      framebuffer.push_back(channel);
      framebuffer_hash = fnv1a(framebuffer_hash, channel & 0xffu);
      framebuffer_hash = fnv1a(framebuffer_hash, channel >> 8);
    }
  }
  uint64_t corpus_hash = 1469598103934665603ull;
  for (unsigned char byte : state)
    corpus_hash = fnv1a(corpus_hash, byte);
  for (uint16_t channel : framebuffer) {
    corpus_hash = fnv1a(corpus_hash, channel & 0xffu);
    corpus_hash = fnv1a(corpus_hash, channel >> 8);
  }

  std::ofstream out(argv[1], std::ios::binary | std::ios::trunc);
  if (!out) {
    std::fprintf(stderr, "cannot open %s\n", argv[1]);
    return 1;
  }
  out << "/*\n"
         " * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.\n"
         " * Licensed under the Polyform Noncommercial License 1.0.0\n"
         " * Generated by tools/mindsplatter_replay_gen.cpp.\n"
         " */\n"
         "#pragma once\n\n"
         "#include \"core/engine/platform.h\"\n\n"
         "#include <cstddef>\n"
         "#include <cstdint>\n\n"
         "namespace mindsplatter_replay {\n\n"
         "struct GoldenPixel {\n"
         "  uint16_t index;\n"
         "  uint16_t r;\n"
         "  uint16_t g;\n"
         "  uint16_t b;\n"
         "};\n\n"
         "enum CorpusTraits : uint32_t {\n"
         "  CORPUS_SATURATED = 1u << 0,\n"
         "  CORPUS_POLE = 1u << 1,\n"
         "  CORPUS_SEAM = 1u << 2,\n"
         "  CORPUS_LONG_EDGE = 1u << 3,\n"
         "  CORPUS_ONE_DOT_HEAVY = 1u << 4,\n"
         "  CORPUS_MEASURED_WORST = 1u << 5,\n"
         "};\n\n"
         "struct Corpus {\n"
         "  const char *id;\n"
         "  const char *source;\n"
         "  int8_t preset;\n"
         "  uint32_t traits;\n"
         "  const unsigned char *state;\n"
         "  size_t state_size;\n"
         "  const GoldenPixel *framebuffer;\n"
         "  size_t framebuffer_entries;\n"
         "  uint16_t particle_count;\n"
         "  uint64_t corpus_hash;\n"
         "  uint64_t framebuffer_hash;\n"
         "};\n\n";
  emit_array(out, "unsigned char", "DENSE_PRESET0_F136_STATE", state, 16);
  emit_golden(out, golden);
  out << "inline const Corpus DENSE_PRESET0_F136 = {\n"
      << "    \"" << CORPUS_ID << "\",\n"
      << "    \"" << SOURCE_ID << "\",\n"
      << "    0,\n"
      << "    0,\n"
      << "    DENSE_PRESET0_F136_STATE,\n"
      << "    sizeof(DENSE_PRESET0_F136_STATE),\n"
      << "    DENSE_PRESET0_F136_FRAMEBUFFER,\n"
      << "    sizeof(DENSE_PRESET0_F136_FRAMEBUFFER) / sizeof(GoldenPixel),\n"
      << "    " << snapshot.particles.size() << ",\n"
      << "    " << corpus_hash << "ull,\n"
      << "    " << framebuffer_hash << "ull};\n\n"
      << "inline const Corpus *const CORPUS_MANIFEST[] = {\n"
      << "    &DENSE_PRESET0_F136};\n\n"
      << "} // namespace mindsplatter_replay\n";
  hs::clear_mock_time();
  std::printf("%s: particles=%zu state=%zu framebuffer=%zu hash=%llu\n",
              CORPUS_ID, snapshot.particles.size(), state.size(),
              framebuffer.size() * sizeof(uint16_t),
              static_cast<unsigned long long>(corpus_hash));
  return out ? 0 : 1;
}
