file(SHA256 "${WASM}" WASM_DIGEST)
file(READ "${GLUE}" SOURCE)
set(NEEDLE "new URL(\"holosphere_wasm.wasm\",")
set(VERSIONED "new URL(\"holosphere_wasm.wasm?v=${WASM_DIGEST}\",")
string(FIND "${SOURCE}" "${VERSIONED}" ALREADY_VERSIONED)
if(NOT ALREADY_VERSIONED EQUAL -1)
  return()
endif()
string(FIND "${SOURCE}" "${NEEDLE}" LOCATION)
if(LOCATION EQUAL -1)
  message(FATAL_ERROR "WASM glue has no expected binary URL: ${GLUE}")
endif()
string(REPLACE "${NEEDLE}" "${VERSIONED}" SOURCE "${SOURCE}")
file(WRITE "${GLUE}" "${SOURCE}")
