file(SHA256 "${WASM}" WASM_DIGEST)
file(READ "${GLUE}" SOURCE)
set(URL_PATTERN "(new[ \t\r\n]+URL[ \t\r\n]*\\([ \t\r\n]*[\"'])holosphere_wasm[.]wasm([?]v=[0-9a-f]+)?([\"'][ \t\r\n]*,)")
if(NOT SOURCE MATCHES "${URL_PATTERN}")
  message(FATAL_ERROR "WASM glue has no expected binary URL: ${GLUE}")
endif()
string(REGEX REPLACE "${URL_PATTERN}"
  "\\1holosphere_wasm.wasm?v=${WASM_DIGEST}\\3" VERSIONED "${SOURCE}")
if(NOT VERSIONED STREQUAL SOURCE)
  file(WRITE "${GLUE}" "${VERSIONED}")
endif()
