/*
 * Required Notice: Copyright 2025 Gabriel Levy. All rights reserved.
 * Licensed under the PolyForm Noncommercial License 1.0.0
 */
#pragma once

// Generated by scripts/generate_composed_presets.mjs.
#include "effects/AlienBrain.h"
#include "effects/AlienCore.h"
#include "effects/AlienOcean.h"
#include "effects/AshCloud.h"
#include "effects/ChromaticLichen.h"
#include "effects/CosmicEyeball.h"
#include "effects/GridSpace.h"
#include "effects/JewelMelt.h"
#include "effects/KaleidoscopeFlowers.h"
#include "effects/KaleidoscopeHexBright.h"
#include "effects/KaleidoscopeHexOil.h"
#include "effects/KaleidoscopeHexSoft.h"
#include "effects/KaleidoscopeMandala.h"
#include "effects/KaleidoscopePentBright.h"
#include "effects/KaleidoscopeSmooth.h"
#include "effects/KaleidoscopeStainedGlass.h"
#include "effects/LatticeMelt.h"
#include "effects/MermaidSkin.h"
#include "effects/MobiusGrid.h"
